[package]
name = "cargolifter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargolifter-core = { path = "../core" }
cargolifter-backend-gitlab = { path = "../backend-gitlab" }
cargolifter-web = { path = "../web" }
futures = "0.3"
tokio = { version = "1.14", features = ["rt", "macros"] }
tracing-subscriber = "0.3"