[package]
name = "cargolifter-storage-filesystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
cargolifter-core = { path = "../core" }
tracing = "0.1"